//------------------------------------------------------------------------------------------------
// Keep HOTAS_Config.conf generation aligned with the proven web configurator output.
// This is separated during the test branch so the generated file format is easy to compare.
modded class HOTASBindingsSubMenu
{
	//------------------------------------------------------------------------------------------------
	override protected void EnsureManagedConfig()
	{
		FileIO.MakeDirectory(CONFIG_DIRECTORY);
		bool owned = false;

		if (FileIO.FileExists(MANAGED_CONFIG_PATH))
		{
			FileHandle existing = FileIO.OpenFile(MANAGED_CONFIG_PATH, FileMode.READ);
			if (existing)
			{
				string firstLine;
				if (existing.ReadLine(firstLine) > 0 && firstLine == MANAGED_SIGNATURE)
					owned = true;
				existing.Close();
			}
		}

		if (!owned)
		{
			ClearBindings();
			WriteManagedConfig();
			SetEditorStatus("Created a fresh HOTAS_Config.conf.");
			return;
		}

		// Always rebuild the in-memory model from the file. This prevents a binding that
		// was removed from the file from surviving in memory and being written back later.
		ClearBindings();
		LoadConfigIntoBindings(MANAGED_CONFIG_PATH, true);
	}

	//------------------------------------------------------------------------------------------------
	protected bool NeedsNegativeMultiplier(HOTASBindingDefinition definition)
	{
		if (definition.m_sConfigAction == "PFC_Pitch" && definition.m_sFilterPreset == "forward")
			return true;
		if (definition.m_sConfigAction == "PFC_Roll" && definition.m_sFilterPreset == "left")
			return true;
		if (definition.m_sConfigAction == "PFC_Yaw" && definition.m_sFilterPreset == "left")
			return true;
		return false;
	}

	//------------------------------------------------------------------------------------------------
	override protected void WriteSpecialFilter(FileHandle file, HOTASBindingDefinition definition, int definitionIndex)
	{
		string filterGuid = MakeGuidPrefix("C", definitionIndex);

		if (definition.m_sConfigAction == "CharacterNextWeapon")
		{
			file.WriteLine(string.Format("      Filter InputFilterSingleClick \"%1\" {", filterGuid));
			file.WriteLine("      }");
			return;
		}

		if (definition.m_sConfigAction == "TurretNextWeapon")
		{
			file.WriteLine(string.Format("      Filter InputFilterHoldOnce \"%1\" {", filterGuid));
			file.WriteLine("       HoldDuration 25");
			file.WriteLine("      }");
			return;
		}

		if (definition.m_sConfigAction == "SelectAction" || definition.m_sConfigAction == "HelicopterSightZeroing")
		{
			file.WriteLine(string.Format("      Filter InputFilterRepeat \"%1\" {", filterGuid));
			if (definition.m_sFilterPreset == "next" || definition.m_sFilterPreset == "down")
				file.WriteLine("       Multiplier -1");
			file.WriteLine("      }");
			return;
		}

		if (NeedsNegativeMultiplier(definition))
		{
			file.WriteLine(string.Format("      Filter InputFilterValue \"%1\" {", filterGuid));
			file.WriteLine("       Multiplier -1");
			file.WriteLine("      }");
			return;
		}

		if (definition.m_sFilterPreset == "toggle")
		{
			file.WriteLine(string.Format("      Filter InputFilterDown \"%1\" {", filterGuid));
			file.WriteLine("      }");
			return;
		}

		if (definition.m_sFilterPreset == "hold" && (definition.m_sConfigAction.Contains("Engine") || definition.m_sConfigAction.Contains("ADS")))
		{
			file.WriteLine(string.Format("      Filter InputFilterHold \"%1\" {", filterGuid));
			if (definition.m_sConfigAction.Contains("ADSHold"))
				file.WriteLine("       HoldDuration -1");
			file.WriteLine("      }");
			return;
		}

		if (definition.m_sConfigAction.Contains("Reset"))
		{
			file.WriteLine(string.Format("      Filter InputFilterSingleClick \"%1\" {", filterGuid));
			file.WriteLine("      }");
			return;
		}

		if (definition.m_sConfigAction == "HelicopterSightDeploy" || definition.m_sConfigAction == "VehicleDoorToggle")
		{
			file.WriteLine(string.Format("      Filter InputFilterClick \"%1\" {", filterGuid));
			file.WriteLine("      }");
			return;
		}

		if (definition.m_sConfigAction.Contains("EngineStop"))
		{
			file.WriteLine(string.Format("      Filter InputFilterHoldOnce \"%1\" {", filterGuid));
			file.WriteLine("      }");
		}
	}

	//------------------------------------------------------------------------------------------------
	override protected bool WriteManagedConfig()
	{
		FileIO.MakeDirectory(CONFIG_DIRECTORY);
		FileHandle file = FileIO.OpenFile(MANAGED_CONFIG_PATH, FileMode.WRITE);
		if (!file)
		{
			SetEditorStatus("ERROR: Could not write HOTAS_Config.conf.");
			return false;
		}

		file.WriteLine(MANAGED_SIGNATURE);
		file.WriteLine("// This file is fully regenerated by Reforger HOTAS Debugger.");
		file.WriteLine("// Other custom input configs are read-only to this mod.");
		file.WriteLine("ActionManager {");
		file.WriteLine(" Actions {");

		for (int i = 0; i < m_Definitions.Count(); i++)
		{
			if (!IsFirstDefinitionForConfigAction(i))
				continue;

			HOTASBindingDefinition firstDefinition = m_Definitions[i];
			string configAction = firstDefinition.m_sConfigAction;
			if (!HasBindingForConfigAction(configAction))
				continue;

			file.WriteLine(string.Format("  Action %1 {", configAction));
			if (configAction == "SelectAction" || configAction == "HelicopterSightZeroing")
				file.WriteLine("   Type AnalogRelative");
			file.WriteLine(string.Format("   InputSource InputSourceSum \"%1\" {", MakeGuidPrefix("A", i)));
			file.WriteLine("    Sources {");

			for (int j = 0; j < m_Definitions.Count(); j++)
			{
				HOTASBindingDefinition definition = m_Definitions[j];
				if (definition.m_sConfigAction != configAction || m_Bindings[j].IsEmpty())
					continue;

				string input = m_Bindings[j];
				if (definition.m_bFullAxis && input.Length() > 0)
				{
					string lastCharacter = input.Substring(input.Length() - 1, 1);
					if (lastCharacter == "+" || lastCharacter == "-")
						input = input.Substring(0, input.Length() - 1);
				}

				file.WriteLine(string.Format("     InputSourceValue \"%1\" {", MakeGuidPrefix("B", j)));
				file.WriteLine(string.Format("      FilterPreset \"%1\"", definition.m_sFilterPreset));
				file.WriteLine(string.Format("      Input \"%1\"", input));
				WriteSpecialFilter(file, definition, j);
				file.WriteLine("     }");
			}

			file.WriteLine("    }");
			file.WriteLine("   }");
			file.WriteLine("  }");
		}

		file.WriteLine(" }");
		file.WriteLine("}");
		file.Close();
		return true;
	}
}
