MenuManager : "{C747AFB6B750CE9A}Configs/System/chimeraMenus.conf" {
 MenuPresets {
  MenuPreset HOTASSettingsMenu {
   Layout "{267FA2655D58593F}UI/layouts/Menus/HOTAS/HOTASSettingsMenu.layout"
   ActionContext "MenuContext"
   Class "HOTASSettingsMenu"
  }
 }
}
