ActionManager : "{795184CF9AD764DB}Configs/System/chimeraInputCommon.conf" {
 Actions {
  Action HOTASSettingsToggle {
   Type Digital
   InputSource InputSourceValue "{AD92A2867A4883AD}" {
    Input "keyboard:KC_F10"
    Filter InputFilterClick "{B61E033C038CCDE2}" {
    }
   }
  }
 }
 Contexts {
  ActionContext IngameContext {
   ActionRefs +{
    "HOTASSettingsToggle"
   }
  }
  ActionContext MenuContext {
   ActionRefs +{
    "HOTASSettingsToggle"
   }
  }
 }
}
