SCR_KeyBindingMenuConfig : "{4EE7794C9A3F11EF}Configs/System/keyBindingMenu.conf" {
 m_KeyBindingCategories +{
  SCR_KeyBindingCategory "{E0C08DB40013A8FC}" {
   m_sName "HOTASInputHUD"
   m_sDisplayName "HOTAS Input HUD"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{0F82DBF4650F71BE}" {
     m_sActionName "HOTASSettingsToggle"
     m_sDisplayName "Open HUD Settings"
     m_sPreset "click"
    }
   }
  }
 }
}
