from pathlib import Path

path = Path("Scripts/Game/HOTASDebugger/HOTASDebugger.c")
src = path.read_text(encoding="utf-8")

old = '''\t\t\t\tstring normalizedBinding = NormalizeAxisBinding(binding);\n\t\t\t\tstring axisName = GetFreelookLabelForAction(actionName);\n\t\t\t\tif (!axisName.IsEmpty())\n\t\t\t\t{\n\t\t\t\t\treadable = axisName;\n\t\t\t\t}\n\t\t\t\telse if (!m_sRollAxisBinding.IsEmpty() && normalizedBinding == m_sRollAxisBinding)\n\t\t\t\t\taxisName = m_sRollAxisLabel;\n\t\t\t\telse if (!m_sPitchAxisBinding.IsEmpty() && normalizedBinding == m_sPitchAxisBinding)\n\t\t\t\t\taxisName = m_sPitchAxisLabel;\n\t\t\t\telse if (!m_sThrottleAxisBinding.IsEmpty() && normalizedBinding == m_sThrottleAxisBinding)\n\t\t\t\t\taxisName = m_sThrottleAxisLabel;\n\t\t\t\telse if (!m_sYawAxisBinding.IsEmpty() && normalizedBinding == m_sYawAxisBinding)\n\t\t\t\t\taxisName = m_sYawAxisLabel;\n\n\t\t\t\tif (!GetFreelookLabelForAction(actionName).IsEmpty())\n\t\t\t\t{\n\t\t\t\t\t// Direction is already part of the user's text (for example "Thumbstick Up").\n\t\t\t\t}\n\t\t\t\telse if (!axisName.IsEmpty())\n\t\t\t\t\treadable = string.Format("%1 %2", axisName, direction);\n\t\t\t\telse\n\t\t\t\t\treadable = string.Format("AXIS %1%2", rawAxis + 1, direction);'''

new = '''\t\t\t\tstring normalizedBinding = NormalizeAxisBinding(binding);\n\t\t\t\tstring freelookLabel = GetFreelookLabelForAction(actionName);\n\t\t\t\tbool isFreelookDirection = actionName == "FreelookUp"\n\t\t\t\t\t|| actionName == "FreelookDown"\n\t\t\t\t\t|| actionName == "FreelookRight"\n\t\t\t\t\t|| actionName == "FreelookLeft";\n\n\t\t\t\tif (isFreelookDirection)\n\t\t\t\t{\n\t\t\t\t\t// Free Look is direction-specific. A custom value such as "Thumbstick Up"\n\t\t\t\t\t// replaces the raw axis text; an empty value deliberately keeps AXIS N+/-.\n\t\t\t\t\tif (!freelookLabel.IsEmpty())\n\t\t\t\t\t\treadable = freelookLabel;\n\t\t\t\t\telse\n\t\t\t\t\t\treadable = string.Format("AXIS %1%2", rawAxis + 1, direction);\n\t\t\t\t}\n\t\t\t\telse\n\t\t\t\t{\n\t\t\t\t\tstring axisName;\n\t\t\t\t\tif (!m_sRollAxisBinding.IsEmpty() && normalizedBinding == m_sRollAxisBinding)\n\t\t\t\t\t\taxisName = m_sRollAxisLabel;\n\t\t\t\t\telse if (!m_sPitchAxisBinding.IsEmpty() && normalizedBinding == m_sPitchAxisBinding)\n\t\t\t\t\t\taxisName = m_sPitchAxisLabel;\n\t\t\t\t\telse if (!m_sThrottleAxisBinding.IsEmpty() && normalizedBinding == m_sThrottleAxisBinding)\n\t\t\t\t\t\taxisName = m_sThrottleAxisLabel;\n\t\t\t\t\telse if (!m_sYawAxisBinding.IsEmpty() && normalizedBinding == m_sYawAxisBinding)\n\t\t\t\t\t\taxisName = m_sYawAxisLabel;\n\n\t\t\t\t\tif (!axisName.IsEmpty())\n\t\t\t\t\t\treadable = string.Format("%1 %2", axisName, direction);\n\t\t\t\t\telse\n\t\t\t\t\t\treadable = string.Format("AXIS %1%2", rawAxis + 1, direction);\n\t\t\t\t}'''

count = src.count(old)
if count != 1:
    raise RuntimeError(f"expected one MakeReadableBinding Free Look block, found {count}")
src = src.replace(old, new, 1)
path.write_text(src, encoding="utf-8")
